server:
  port: 8081

spring:
  application:
    name: petEvent

  datasource:
    url: jdbc:mysql://localhost:3306/petdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  batch:
    job:
      enabled: false  # 애플리케이션 시작 시 배치 자동 실행 방지
    jdbc:
      initialize-schema: always  # 배치 관련 테이블 자동 생성

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.batch: INFO
    com.playdata.petevent: DEBUG