spring:
  application:
    name: petEvent
  datasource:
    url: jdbc:mysql://localhost:3306/petdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: spring
    password: spring

    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 20MB

  logging:
    level:
      org.hibernate.SQL: debug